n1=int(input("enter number 1:"))
n2=int(input("enter number 2:"))
n3=int(input("enter number 3:"))
n4=int(input("enter number 4:"))
n5=int(input("enter number 5:"))
n6=int(input("enter number 6:"))
n7=int(input("enter number 7:"))
n8=int(input("enter number 8:"))
s=set()
s.add(n1)
s.add(n2)
s.add(n3)
s.add(n4)
s.add(n5)
s.add(n6)
s.add(n7)
s.add(n8)
print(s)
